### ISSUE TITLE
Some Issues with the project in general

### ISSUE THREAD

**Issue by mcworkaholic** [AYehia0/soundcloud-dl#4]
First off, love it so far, but there are some clear issues here. (Windows 11 - Powershell - American - go1.20.3)

-Your personal ClientId should not be hardcoded as our clientId for access to our music, it should be our own unique Id. What if you decide to delete your account? I've seen your profile as well 😎

-Metadata for every track or playlist I've decided to try to download has not worked. No artwork, title, creator, nothing. Is it because of country differences in the HTML of the URL? Look at this link for an example of a request to a specific song's page [https://soundcloud.com/conspiracy_bass/go-nuts-vip](url). There's a 10-15 line section in it that contains most of the information you need to scrape, as well as the link to the artwork.

-Instead of incorporating separate features in different branches, why don't you just include these as options in the master/main branch? It keeps us from having to clone multiple versions of your project. 

-Why have [low] or [high] in the filename when we can assume it's high quality if it's an .ogg file? Additionally, If we need to look at the quality, couldn't we just look at the details of the file?

-Was this built specifically with Linux in mind?

-  Hoping this doesn't come off as harsh, it's just how I write

**Comment by AYehia0** [comment]
Hello, thanks for the feedback :smiley: 
- I am not hardcoding my `clientId`, if you mean the one in the tests, it's a fake one.  The `clientId` has nothing to do with my soundcloud account, actually the code fetches a the `clientId` : [here](https://github.com/AYehia0/soundcloud-dl/blob/f3c058f23612cf63389fad4954cfda8910972e7b/pkg/soundcloud/page.go#L35)
- I tried the track you gave, it successfully adds the correct metadata to the track : 
```
 Artist: conspiracy_bass
 Date: 2021-07-22T02:02:53Z
 Genre: Dubstep
 Title: GO NUTS
```
- The idea behind having multiple branches is that I didn't know what feature should I include to main also there where some features that I didn't like to have but also I didn't want to update, so I created multiple branches having features like so. but the main/master branch has the latest changes (I guess).
- The low/high quality was some kinda a personal preference here, as I didn't know what to call each track extension lol, also I can't check the file/track as I am downloading it, maybe you can use some kinda tool to check the audio info after downloading and based on that rename, (maybe) but I don't think it's worthy in this case.
- Finally I don't know about other OSs, I don't use windoz but I think it should work properly (didn't try tbh).

**Comment by mcworkaholic** [comment]
Yeah I see where I was wrong with the clientId after looking at it again, and idk what I'm doing wrong with using it, but adding metadata does not work at all for me on Windows 11. Using my own version of your program here, but did not change much besides styling as I'm not familiar with golang.

![image](https://user-images.githubusercontent.com/94456069/233314140-b5733f51-cf60-490c-b565-a78fbb13b750.png)

**Comment by AYehia0** [comment]
This is related to windows not be able to rename the file/track after downloading it.
Idv3v2 (the package I am using to add tags) adds tags to the track with temp name `*-idv2` then renames.

https://github.com/AYehia0/soundcloud-dl/blob/f3c058f23612cf63389fad4954cfda8910972e7b/pkg/soundcloud/metadata.go#L53-L55

**Comment by mcworkaholic** [comment]
Yeah, I figured. I already created my own version that saves to JSON for tag editing with a python script
